export enum Characters {
  March7th = 'March 7th',
  DanHeng = 'Dan Heng',
  Himeko = 'Himeko',
  Welt = 'Welt',
  Kafka = 'Kafka',
  SilverWolf = 'Silver Wolf',
  Arlan = 'Arlan',
  Asta = 'Asta',
  Herta = 'Herta',
  Bronya = 'Bronya',
  Seele = 'Seele',
  Serval = 'Serval',
  Gepard = 'Gepard',
  Natasha = 'Natasha',
  Pela = 'Pela',
  Clara = 'Clara',
  Sampo = 'Sampo',
  Hook = 'Hook',
  Lynx = 'Lynx',
  Luka = 'Luka',
  TopazAndNumby = 'Topaz & Numby',
  Qingque = 'Qingque',
  Tingyun = 'Tingyun',
  Luocha = 'Luocha',
  JingYuan = 'Jing Yuan',
  Blade = 'Blade',
  Sushang = 'Sushang',
  Yukong = 'Yukong',
  FuXuan = 'Fu Xuan',
  Yanqing = 'Yanqing',
  Guinaifen = 'Guinaifen',
  Bailu = 'Bailu',
  Jingliu = 'Jingliu',
  DanHengImbibitorLunae = 'Dan Heng • Imbibitor Lunae',
  Xueyi = 'Xueyi',
  Hanya = 'Hanya',
  HuoHuo = 'HuoHuo',
  Gallagher = 'Gallagher',
  Argenti = 'Argenti',
  RuanMei = 'Ruan Mei',
  Aventurine = 'Aventurine',
  DrRatio = 'Dr. Ratio',
  Sparkle = 'Sparkle',
  BlackSwan = 'Black Swan',
  Acheron = 'Acheron',
  Misha = 'Misha',
  PlayerBoyDestruction = 'PlayerBoyDestruction',
  PlayerGirlDestruction = 'PlayerGirlDestruction',
  PlayerBoyPreservation = 'PlayerBoyPreservation',
  PlayerGirlPreservation = 'PlayerGirlPreservation',
}

export enum CharacterIDs {
  March7th = '1001',
  DanHeng = '1002',
  Himeko = '1003',
  Welt = '1004',
  Kafka = '1005',
  SilverWolf = '1006',
  Arlan = '1008',
  Asta = '1009',
  Herta = '1013',
  Bronya = '1101',
  Seele = '1102',
  Serval = '1103',
  Gepard = '1104',
  Natasha = '1105',
  Pela = '1106',
  Clara = '1107',
  Sampo = '1108',
  Hook = '1109',
  Lynx = '1110',
  Luka = '1111',
  TopazAndNumby = '1112',
  Qingque = '1201',
  Tingyun = '1202',
  Luocha = '1203',
  JingYuan = '1204',
  Blade = '1205',
  Sushang = '1206',
  Yukong = '1207',
  FuXuan = '1208',
  Yanqing = '1209',
  Guinaifen = '1210',
  Bailu = '1211',
  Jingliu = '1212',
  DanHengImbibitorLunae = '1213',
  Xueyi = '1214',
  Hanya = '1215',
  HuoHuo = '1217',
  Gallagher = '1301',
  Argenti = '1302',
  RuanMei = '1303',
  Aventurine = '1304',
  DrRatio = '1305',
  Sparkle = '1306',
  BlackSwan = '1307',
  Acheron = '1308',
  Misha = '1312',
  PlayerBoyDestruction = '8001',
  PlayerGirlDestruction = '8002',
  PlayerBoyPreservation = '8003',
  PlayerGirlPreservation = '8004',
}

export const CharacterToIDs: Record<string, string> = {
  [Characters.March7th]: CharacterIDs.March7th,
  [Characters.Kafka]: Characters.Kafka,
  [Characters.SilverWolf]: Characters.SilverWolf,
  [Characters.Arlan]: Characters.Arlan,
  [Characters.Asta]: Characters.Asta,
  [Characters.Herta]: Characters.Herta,
  [Characters.Bronya]: Characters.Bronya,
  [Characters.Seele]: Characters.Seele,
  [Characters.Serval]: Characters.Serval,
  [Characters.Gepard]: Characters.Gepard,
  [Characters.Natasha]: Characters.Natasha,
  [Characters.Pela]: Characters.Pela,
  [Characters.Clara]: Characters.Clara,
  [Characters.Sampo]: Characters.Sampo,
  [Characters.Hook]: Characters.Hook,
  [Characters.Lynx]: Characters.Lynx,
  [Characters.Luka]: Characters.Luka,
  [Characters.TopazAndNumby]: Characters.TopazAndNumby,
  [Characters.Qingque]: Characters.Qingque,
  [Characters.Tingyun]: Characters.Tingyun,
  [Characters.Luocha]: Characters.Luocha,
  [Characters.JingYuan]: Characters.JingYuan,
  [Characters.Blade]: Characters.Blade,
  [Characters.Sushang]: Characters.Sushang,
  [Characters.Yukong]: Characters.Yukong,
  [Characters.FuXuan]: Characters.FuXuan,
  [Characters.Yanqing]: Characters.Yanqing,
  [Characters.Guinaifen]: Characters.Guinaifen,
  [Characters.Bailu]: Characters.Bailu,
  [Characters.Jingliu]: Characters.Jingliu,
  [Characters.DanHengImbibitorLunae]: Characters.DanHengImbibitorLunae,
  [Characters.Xueyi]: Characters.Xueyi,
  [Characters.Hanya]: Characters.Hanya,
  [Characters.HuoHuo]: Characters.HuoHuo,
  [Characters.Gallagher]: Characters.Gallagher,
  [Characters.Argenti]: Characters.Argenti,
  [Characters.RuanMei]: Characters.RuanMei,
  [Characters.Aventurine]: Characters.Aventurine,
  [Characters.DrRatio]: Characters.DrRatio,
  [Characters.Sparkle]: Characters.Sparkle,
  [Characters.BlackSwan]: Characters.BlackSwan,
  [Characters.Acheron]: Characters.Acheron,
  [Characters.Misha]: Characters.Misha,
  [Characters.PlayerBoyDestruction]: Characters.PlayerBoyDestruction,
  [Characters.PlayerGirlDestruction]: Characters.PlayerGirlDestruction,
  [Characters.PlayerBoyPreservation]: Characters.PlayerBoyPreservation,
  [Characters.PlayerGirlPreservation]: Characters.PlayerGirlPreservation,
};

export enum Resources {
  avatars = 'avatars',
  characterPromotions = 'character_promotions',
  characterRanks = 'character_ranks',
  characterSkillTrees = 'character_skill_trees',
  characterSkills = 'character_skills',
  characters = 'characters',
  descriptions = 'descriptions',
  elements = 'elements',
  items = 'items',
  lightConePromotions = 'light_cone_promotions',
  lightConeRanks = 'light_cone_ranks',
  lightCones = 'light_cones',
  nicknames = 'nicknames',
  paths = 'paths',
  properties = 'properties',
  relicMainAffixes = 'relic_main_affixes',
  relicSets = 'relic_sets',
  relicSubAffixes = 'relic_sub_affixes',
  relics = 'relics',
  simulatedBlessings = 'simulated_blessings',
  simulatedCurious = 'simulated_curious',
  simulatedEvents = 'simulated_events',
}
export enum Stats {
  hp = 'hp',
  atk = 'atk',
  def = 'def',
  spd = 'spd',
  crit = 'taunt',
  dodge = 'crit_rate',
  block = 'crit_dmg',
}

export enum RelicSets {
  PasserbyOfWanderingCloud = 'Passerby of Wandering Cloud',
  MusketeerOfWildWheat = 'Musketeer of Wild Wheat',
  KnightOfPurityPalace = 'Knight of Purity Palace',
  HunterOfGlacialForest = 'Hunter of Glacial Forest',
  ChampionOfStreetwiseBoxing = 'Champion of Streetwise Boxing',
  GuardOfWutheringSnow = 'Guard of Wuthering Snow',
  FiresmithOfLavaForging = 'Firesmith of Lava-Forging',
  GeniusOfBrilliantStars = 'Genius of Brilliant Stars',
  BandOfSizzlingThunder = 'Band of Sizzling Thunder',
  EagleOfTwilightLine = 'Eagle of Twilight Line',
  ThiefOfShootingMeteor = 'Thief of Shooting Meteor',
  LongevousDisciple = 'Longevous Disciple',
  MessengerTraversingHackerspace = 'Messenger Traversing Hackerspace',
  TheAshblazingGrandDuke = 'The Ashblazing Grand Duke',
  PrisonerInDeepConfinement = 'Prisoner in Deep Confinement',
  PioneerDiverOfDeadWaters = 'Pioneer Diver of Dead Waters',
  WatchmakerMasterOfDreamMachinations = 'Watchmaker, Master of Dream Machinations',
  SpaceSealingStation = 'Space Sealing Station',
  FleetOfTheAgeless = 'Fleet of the Ageless',
  PanCosmicCommercialEnterprise = 'Pan-Cosmic Commercial Enterprise',
  BelobogOfTheArchitects = 'Belobog of the Architects',
  CelestialDifferentiator = 'Celestial Differentiator',
  InertSalsotto = 'Inert Salsotto',
  TaliaKingdomOfBanditry = 'Talia: Kingdom of Banditry',
  SprightlyVonwacq = 'Sprightly Vonwacq',
  RutilantArena = 'Rutilant Arena',
  BrokenKeel = 'Broken Keel',
  FirmamentFrontlineGlamoth = 'Firmament Frontline: Glamoth',
  PenaconyLandOfTheDreams = 'Penacony, Land of the Dreams',
  SigoniaTheUnclaimedDesolation = 'Sigonia, the Unclaimed Desolation',
  IzumoGenseiAndTakamaDivineRealm = 'Izumo Gensei and Takama Divine Realm',
}

export enum RelicSetIDs {
  PasserbyOfWanderingCloud = '101',
  MusketeerOfWildWheat = '102',
  KnightOfPurityPalace = '103',
  HunterOfGlacialForest = '104',
  ChampionOfStreetwiseBoxing = '105',
  GuardOfWutheringSnow = '106',
  FiresmithOfLavaForging = '107',
  GeniusOfBrilliantStars = '108',
  BandOfSizzlingThunder = '109',
  EagleOfTwilightLine = '110',
  ThiefOfShootingMeteor = '111',
  WastelanderOfBanditryDesert = '112',
  LongevousDisciple = '113',
  MessengerTraversingHackerspace = '114',
  TheAshblazingGrandDuke = '115',
  PrisonerInDeepConfinement = '116',
  PioneerDiverOfDeadWaters = '117',
  WatchmakerMasterOfDreamMachinations = '118',
  SpaceSealingStation = '301',
  FleetOfTheAgeless = '302',
  PanCosmicCommercialEnterprise = '303',
  BelobogOfTheArchitects = '304',
  CelestialDifferentiator = '305',
  InertSalsotto = '306',
  TaliaKingdomOfBanditry = '307',
  SprightlyVonwacq = '308',
  RutilantArena = '309',
  BrokenKeel = '310',
  FirmamentFrontlineGlamoth = '311',
  PenaconyLandOfTheDreams = '312',
  SigoniaTheUnclaimedDesolation = '313',
  IzumoGenseiAndTakamaDivineRealm = '314',
}

export enum Languages {
  chinese = 'cn',
  chineseTraditional = 'cht',
  german = 'de',
  english = 'en',
  spanish = 'es',
  french = 'fr',
  japanese = 'jp',
  korean = 'kr',
  portuguese = 'pt',
  russian = 'ru',
  taiwanese = 'th',
  vietnamese = 'vi',
}

export enum Properties {
  MaxHP = 'MaxHP',
  Attack = 'Attack',
  Defense = 'Defense',
  Speed = 'Speed',
  CriticalChance = 'CriticalChance',
  CriticalDamage = 'CriticalDamage',
  BreakDamageAddedRatio = 'BreakDamageAddedRatio',
  BreakDamageAddedRatioBase = 'BreakDamageAddedRatioBase',
  HealRatio = 'HealRatio',
  MaxSP = 'MaxSP',
  SpecialMaxSP = 'SpecialMaxSP',
  SPRatio = 'SPRatio',
  StatusProbability = 'StatusProbability',
  StatusResistance = 'StatusResistance',
  CriticalChanceBase = 'CriticalChanceBase',
  CriticalDamageBase = 'CriticalDamageBase',
  HealRatioBase = 'HealRatioBase',
  StanceBreakAddedRatio = 'StanceBreakAddedRatio',
  SPRatioBase = 'SPRatioBase',
  StatusProbabilityBase = 'StatusProbabilityBase',
  StatusResistanceBase = 'StatusResistanceBase',
  PhysicalAddedRatio = 'PhysicalAddedRatio',
  PhysicalResistance = 'PhysicalResistance',
  FireAddedRatio = 'FireAddedRatio',
  FireResistance = 'FireResistance',
  IceAddedRatio = 'IceAddedRatio',
  IceResistance = 'IceResistance',
  ThunderAddedRatio = 'ThunderAddedRatio',
  ThunderResistance = 'ThunderResistance',
  WindAddedRatio = 'WindAddedRatio',
  WindResistance = 'WindResistance',
  QuantumAddedRatio = 'QuantumAddedRatio',
  QuantumResistance = 'QuantumResistance',
  ImaginaryAddedRatio = 'ImaginaryAddedRatio',
  ImaginaryResistance = 'ImaginaryResistance',
  BaseHP = 'BaseHP',
  HPDelta = 'HPDelta',
  HPAddedRatio = 'HPAddedRatio',
  BaseAttack = 'BaseAttack',
  AttackDelta = 'AttackDelta',
  AttackAddedRatio = 'AttackAddedRatio',
  BaseDefense = 'BaseDefence',
  DefenseDelta = 'DefenceDelta',
  DefenseAddedRatio = 'DefenceAddedRatio',
  BaseSpeed = 'BaseSpeed',
  HealTakenRatio = 'HealTakenRatio',
  PhysicalResistanceDelta = 'PhysicalResistanceDelta',
  FireResistanceDelta = 'FireResistanceDelta',
  IceResistanceDelta = 'IceResistanceDelta',
  ThunderResistanceDelta = 'ThunderResistanceDelta',
  WindResistanceDelta = 'WindResistanceDelta',
  QuantumResistanceDelta = 'QuantumResistanceDelta',
  ImaginaryResistanceDelta = 'ImaginaryResistanceDelta',
  SpeedDelta = 'SpeedDelta',
  SpeedAddedRatio = 'SpeedAddedRatio',
  AllDamageTypeAddedRatio = 'AllDamageTypeAddedRatio',
}

export enum Paths {
  Destruction = 'Warrior',
  TheHunt = 'Rogue',
  Erudition = 'Mage',
  Harmony = 'Shaman',
  Nihility = 'Warlock',
  Preservation = 'Knight',
  Abundance = 'Priest',
  General = 'Unknown',
}
